// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package icons

import (
	_ "embed"
	"fyne.io/fyne/v2"
)

//go:embed tray_black.png
var resourceTrayblackPngData []byte
var resourceTrayblackPng = &fyne.StaticResource{
	StaticName:    "./internal/ui/icons/tray_black.png",
	StaticContent: resourceTrayblackPngData,
}

//go:embed tray_white.png
var resourceTraywhitePngData []byte
var resourceTraywhitePng = &fyne.StaticResource{
	StaticName:    "./internal/ui/icons/tray_white.png",
	StaticContent: resourceTraywhitePngData,
}
